In [84]:
import numpy as np

N = 1000
E = 2000
V = 200
x = np.random.rand(N, E)
index = np.random.randint(V, size=E)
y = np.zeros((N, V))

In [85]:
def scatter_add(x:np.ndarray, index:np.ndarray, y:np.ndarray) -> np.ndarray:
    for k, i in enumerate(index):
        y[..., i] += x[..., k]
    return y
y *= 0
scatter_add(x, index, y)

array([[ 2.36198413,  5.65710635,  3.31353951, ...,  4.82809586,
         6.50857762,  8.46213998],
       [ 3.52846192,  6.38426892,  4.15126881, ...,  3.50748094,
         6.12743827,  6.65821791],
       [ 2.40151283,  6.24376193,  3.58312421, ...,  3.64625663,
         8.7896405 ,  8.00714783],
       ...,
       [ 2.72916714,  5.86078715,  3.41749477, ...,  4.61200261,
         7.13125831,  9.3423487 ],
       [ 2.993575  ,  5.45736698,  3.43110442, ...,  3.65252061,
         7.37096137, 10.09552942],
       [ 3.92841941,  6.0291518 ,  4.74540909, ...,  4.01899022,
         6.58053639,  5.16243332]])

In [86]:
y *= 0

In [87]:
%%timeit
scatter_add(x, index, y)

5.28 ms ± 303 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [97]:
from numba import njit, prange

@njit(parallel=True)
def scatter_add_numba(x: np.ndarray, index: np.ndarray, y: np.ndarray) -> np.ndarray:
    # 假设 x, y 都是 2D，沿第 0 维索引累加
    N, E = x.shape
    for e in prange(E):
        v = index[e]
        for d in range(N):
            y[d, v] += x[d, e]
    return y
y *= 0
scatter_add_numba(x, index, y)

array([[ 2.36198413,  5.65710635,  3.31353951, ...,  4.82809586,
         6.50857762,  8.46213998],
       [ 3.52846192,  6.38426892,  4.15126881, ...,  3.50748094,
         6.12743827,  6.65821791],
       [ 2.40151283,  6.24376193,  3.58312421, ...,  3.64625663,
         8.7896405 ,  8.00714783],
       ...,
       [ 2.72916714,  5.86078715,  3.41749477, ...,  4.61200261,
         7.13125831,  9.3423487 ],
       [ 2.993575  ,  5.45736698,  3.43110442, ...,  3.65252061,
         7.37096137, 10.09552942],
       [ 3.92841941,  6.0291518 ,  4.74540909, ...,  4.01899022,
         6.58053639,  5.16243332]])

In [98]:
y *= 0

In [99]:
%%timeit
scatter_add_numba(x, index, y)

1.26 ms ± 259 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
from numba import njit, prange

@njit(parallel=True)
def scatter_add_numba_T(x: np.ndarray, index: np.ndarray, y: np.ndarray) -> np.ndarray:
    # 假设 x, y 都是 2D，沿第 1 维索引累加
    N, E = x.shape
    for n in prange(N):
        v = index[n]
        for e in range(E):
            y[v, e] += x[n, e]
    return y
y *= 0
scatter_add_numba_T(x, index, y)

array([[1.17499447, 1.22212153, 0.45762728, ..., 0.72677066, 0.98338105,
        1.28917099],
       [4.90679784, 4.76822995, 4.16839873, ..., 3.49816393, 4.52690098,
        4.32884373],
       [6.95724397, 5.80391087, 5.7160583 , ..., 6.81040709, 6.98763999,
        6.52531372],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [111]:
from numba import njit, prange

@njit(parallel=True)
def scatter_add_numba_T(x: np.ndarray, index: np.ndarray, y: np.ndarray) -> np.ndarray:
    # 假设 x, y 都是 2D，沿第 1 维索引累加
    N, E = x.shape
    for e in prange(E):
        v = index[e]
        for n in prange(N):
            y[n, v] += x[n, e]
    return y
y *= 0
scatter_add_numba_T(x, index, y)

array([[ 2.36198413,  5.65710635,  3.31353951, ...,  4.82809586,
         6.50857762,  8.46213998],
       [ 3.52846192,  6.38426892,  4.15126881, ...,  3.50748094,
         6.12743827,  6.65821791],
       [ 2.40151283,  6.24376193,  3.58312421, ...,  3.64625663,
         8.7896405 ,  8.00714783],
       ...,
       [ 2.72916714,  5.86078715,  3.41749477, ...,  4.61200261,
         7.13125831,  9.3423487 ],
       [ 2.993575  ,  5.45736698,  3.43110442, ...,  3.65252061,
         7.37096137, 10.09552942],
       [ 3.92841941,  6.0291518 ,  4.74540909, ...,  4.01899022,
         6.58053639,  5.16243332]])

In [112]:
y *= 0

In [113]:
%%timeit
scatter_add_numba_T(x, index, y)

1.19 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [94]:
import numpy as np

def scatter_add_np(x: np.ndarray, index: np.ndarray, y: np.ndarray) -> np.ndarray:
    """
    对 y 的最后一个轴按 index 做累加，等价于：
        for k, i in enumerate(index):
            y[..., i] += x[..., k]
    """
    # 构造一个切片元组，用于选择 y[..., index]
    # 对于任意维度数的 x/y，这里都把 index 放在最后一维
    # 例如 x.shape=(M1,...,Mh,K), y.shape=(M1,...,Mh,N)
    slc = (Ellipsis, index)
    # 然后在 C 层完成累加
    np.add.at(y, slc, x)
    return y

y *= 0
scatter_add_np(x, index, y)

array([[ 2.36198413,  5.65710635,  3.31353951, ...,  4.82809586,
         6.50857762,  8.46213998],
       [ 3.52846192,  6.38426892,  4.15126881, ...,  3.50748094,
         6.12743827,  6.65821791],
       [ 2.40151283,  6.24376193,  3.58312421, ...,  3.64625663,
         8.7896405 ,  8.00714783],
       ...,
       [ 2.72916714,  5.86078715,  3.41749477, ...,  4.61200261,
         7.13125831,  9.3423487 ],
       [ 2.993575  ,  5.45736698,  3.43110442, ...,  3.65252061,
         7.37096137, 10.09552942],
       [ 3.92841941,  6.0291518 ,  4.74540909, ...,  4.01899022,
         6.58053639,  5.16243332]])

In [95]:
y *= 0

In [96]:
%%timeit
scatter_add(x, index, y)

4.76 ms ± 269 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
